# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AgyMcp < Formula
  desc "Model Context Protocol (MCP) server for Google Antigravity CLI (agy)"
  homepage "https://github.com/tphakala/agy-mcp"
  version "2.8.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/tphakala/agy-mcp/releases/download/v2.8.1/agy-mcp_2.8.1_darwin_amd64.tar.gz"
      sha256 "36cfb743eee3eb9287b002661f0132ac2ba282270512569074df8f8c34b77b66"

      define_method(:install) do
        bin.install "agy-mcp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/tphakala/agy-mcp/releases/download/v2.8.1/agy-mcp_2.8.1_darwin_arm64.tar.gz"
      sha256 "5a27fad64ec01895c2a8fd707932fd2385fe9ede583c9c65790a69ca03398311"

      define_method(:install) do
        bin.install "agy-mcp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/tphakala/agy-mcp/releases/download/v2.8.1/agy-mcp_2.8.1_linux_amd64.tar.gz"
      sha256 "f9a0cfc558179defe6b5af4dcd7211b8738da142a45ee6214b3819ecfcbc9b8f"
      define_method(:install) do
        bin.install "agy-mcp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/tphakala/agy-mcp/releases/download/v2.8.1/agy-mcp_2.8.1_linux_arm64.tar.gz"
      sha256 "ef423779b0047cf0d7cffa9a31d1714896ef72b3dfe141c9ddf313860cd1e6b2"
      define_method(:install) do
        bin.install "agy-mcp"
      end
    end
  end

  test do
    system "#{bin}/agy-mcp", "-h"
  end
end
