# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BirdnetGoRemoteMic < Formula
  desc "Remote microphone appliance for BirdNET-Go (ALSA capture served over RTSP)"
  homepage "https://github.com/tphakala/birdnet-go-remote-mic"
  version "0.1.0"
  license "MIT"
  depends_on :linux

  if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
    url "https://github.com/tphakala/birdnet-go-remote-mic/releases/download/v0.1.0/birdnet-go-remote-mic_0.1.0_linux_amd64.tar.gz"
    sha256 "8509009666a3bc7442dad95a6d43c429a4ae88b0ee2a8eb1c55d938cb16b2b2e"
    define_method(:install) do
      bin.install "remote-mic"
    end
  end
  if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/tphakala/birdnet-go-remote-mic/releases/download/v0.1.0/birdnet-go-remote-mic_0.1.0_linux_arm64.tar.gz"
    sha256 "2abc81dec4bf69abfa6067b91b7b4b94923f86ff0fbf3a49f34ca31784df690e"
    define_method(:install) do
      bin.install "remote-mic"
    end
  end

  def caveats
    <<~EOS
      This installs the `remote-mic` command. To run it at boot as a hardened
      systemd service (creates a dedicated user, unit, and state directories):
        sudo remote-mic service install
    EOS
  end

  test do
    system "#{bin}/remote-mic", "version"
  end
end
