# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BirdnetGoRemoteMic < Formula
  desc "Remote microphone appliance for BirdNET-Go (ALSA capture served over RTSP)"
  homepage "https://github.com/tphakala/birdnet-go-remote-mic"
  version "0.2.0"
  license "MIT"
  depends_on :linux

  if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
    url "https://github.com/tphakala/birdnet-go-remote-mic/releases/download/v0.2.0/birdnet-go-remote-mic_0.2.0_linux_amd64.tar.gz"
    sha256 "bda0fe28a2da0812eff8ab66e5119470bd33966e6d2e9e58a39640ec964fee9a"
    define_method(:install) do
      bin.install "remote-mic"
    end
  end
  if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
    url "https://github.com/tphakala/birdnet-go-remote-mic/releases/download/v0.2.0/birdnet-go-remote-mic_0.2.0_linux_armv6.tar.gz"
    sha256 "aa120ad63f5d613fb75cb9415dcb11f163adf9eb289aa5d327255f93919141e5"
    define_method(:install) do
      bin.install "remote-mic"
    end
  end
  if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/tphakala/birdnet-go-remote-mic/releases/download/v0.2.0/birdnet-go-remote-mic_0.2.0_linux_arm64.tar.gz"
    sha256 "0fe37d8a2fb3c9cc665f33572f64a91a10c47c9f9996be191d57854fe78b84b6"
    define_method(:install) do
      bin.install "remote-mic"
    end
  end

  def caveats
    <<~EOS
      This installs the `remote-mic` command. To run it at boot as a hardened
      systemd service (creates a dedicated user, unit, and state directories):
        sudo remote-mic service install
    EOS
  end

  test do
    system "#{bin}/remote-mic", "version"
  end
end
